version: '3.1'

services:
  mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ./.mongo/db:/data/db
        - ./.mongo/configdb:/data/configdb
        - ./.mongo/init:/docker-entrypoint-initdb.d
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: session
        TZ: Asia/Tokyo


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
    depends_on:
      - mongo

volumes:
  mongo:
